#!/bin/bash

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

TYPE=""
if [ "$1" -eq 0 ]; then
	TYPE="ARCHIVED"
elif [ "$1" -eq 1 ]; then
	TYPE="ARCHIVED_AND_ENCRYPTED"
elif [ "$1" -eq 2 ]; then
	TYPE="ENCRYPTED_AND_INDEXED"
elif [ "$1" -eq 3 ]; then
	TYPE="INDEXED"
else
	exit 1
fi

MAIN_CID=""
if [ ! "$2" ]; then
	exit 1
else
	MAIN_CID="$2"
fi

PASS=""
if [ "$TYPE" = "ARCHIVED_AND_ENCRYPTED" ] || [ "$TYPE" = "ENCRYPTED_AND_INDEXED" ]; then
	if [ ! "$3" ]; then
		exit 1
	else
		PASS="$3"
	fi
fi
	
DEINDEX=false
if [ "$TYPE" = "ENCRYPTED_AND_INDEXED" ] && [ "$4" = true ]; then
	DEINDEX=true	
elif [ "$TYPE" = "INDEXED" ] && [ "$3" = true ]; then
	DEINDEX=true	
fi


function remove_dir {
	if [ -d "$1" ]; then
		rm -r "$1"
	fi
}

function remove_file {
	if [ -f "$1" ]; then
		rm "$1"
	fi
}

#MOVE TO RIGHT PLACE, CREATE DIRECTORIES

mkdir -p ~/.omnidisk
mkdir -p ~/.omnidisk/store
mkdir -p ~/.omnidisk/store/"$MAIN_CID"
cd ~/.omnidisk/store/"$MAIN_CID"
STOREPATH=`echo $PWD`

#########################################################

if [ "$TYPE" = "ARCHIVED" ]; then
	cid=`ipfs cat "$MAIN_CID" | tail -1` #get cid of archive
	ipfs cat "$cid" | unpigz | tar -xf -

elif [ "$TYPE" = "ARCHIVED_AND_ENCRYPTED" ]; then
	cid=`ipfs cat "$MAIN_CID" | tail -1` #get archive
	ipfs cat "$cid" | gpg --batch -d --passphrase "$PASS" | unpigz  | tar -xf -

	echo kokica
	
elif [ "$TYPE" = "ENCRYPTED_AND_INDEXED" ]; then
	cid=`ipfs cat "$MAIN_CID" | head -1` #get cid of INDEX_FILE_priv.gpg
	ipfs cat "$cid" | gpg --batch -d --passphrase "$PASS" > INDEX_FILE_priv

	if [ "$DEINDEX" = "true" ]; then
		cid=`ipfs cat "$MAIN_CID" | head -2 | tail -1` #cid of INDEX TREE
		ipfs cat "$cid" | gpg --batch -d --passphrase "$PASS" | unpigz | tar -xf -
	else
		cid=`ipfs cat "$MAIN_CID" | tail -1` #get cid  all the uploaded content
		ipfs get $cid 

		#TODO search index file for matching cid to get folder name and rename
		#search
		#mv $cid $name
		#cd $name

		cd $cid
		ORG_PATH=`echo $PWD`
		for file in `find . -type f`; do
			cd `dirname "$file"`
			gpg --batch -d --passphrase "$PASS" `basename "$file"` | unpigz | tar -xf - && rm `basename "$file"`
			cd "$ORG_PATH"
		done
	fi

elif [ "$TYPE" = "INDEXED" ]; then

	cid=`ipfs cat "$MAIN_CID" | head -1` #get cid of INDEX_FILE_priv
	ipfs cat "$cid" > INDEX_FILE_priv

	if [ "$DEINDEX" = "true" ]; then
		cid=`ipfs cat "$MAIN_CID" | head -2 | tail -1` #cid of INDEX TREE
		ipfs cat "$cid" | unpigz | tar -xf -
	else
		cid=`ipfs cat "$MAIN_CID" | tail -1` #get cid  all the uploaded content
		ipfs get $cid 

		#TODO search index file for matching cid to get folder name and rename
		#search
		#mv $cid $name
		#cd $name
		cd $cid
		ORG_PATH=`echo $PWD`
		for file in `find . -type f`; do
			cd `dirname "$file"`
			cat `basename "$file"` | unpigz | tar -xf - && rm `basename "$file"`
			cd "$ORG_PATH"
		done

	fi
fi


IFS=$SAVEIFS
